# Generated by Django 3.2.18 on 2023-03-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230319_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='postReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('Rejected', 'Rejected'), ('InReview', 'In Review'), ('Approved', 'Approved')], default='InReview', max_length=200, verbose_name='Review')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post', to_field='slug')),
            ],
        ),
    ]
