# Generated by Django 3.2.18 on 2023-04-01 05:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_postreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list,
                                                                       null=False, blank=False, unique=True, size=None)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
            },
        ),
    ]
