# Generated by Django 3.2.18 on 2023-04-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_coinindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True,
                                   upload_to='post/vd_uploads'),
        ),
        migrations.CreateModel(
            name='imageShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image_slide', models.ImageField(
                    null=True, upload_to='post/sldh')),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='backend.post', to_field='slug')),
            ],
        ),
    ]
