# Generated by Django 3.2.18 on 2023-04-09 13:47

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20230406_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_topic',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Sub Topic'),
        ),
        migrations.AlterField(
            model_name='imageshow',
            name='image_slide',
            field=models.ImageField(null=True, upload_to=backend.models.update_filename),
        ),
    ]
